export const countryCodes = [
    { code: "+1", name: "US/CA", label: "+1 (US/CA)" },
    { code: "+7", name: "Russia/Kazakhstan", label: "+7 (RU/KZ)" },
    { code: "+20", name: "Egypt", label: "+20 (EG)" },
    { code: "+27", name: "South Africa", label: "+27 (ZA)" },
    { code: "+30", name: "Greece", label: "+30 (GR)" },
    { code: "+31", name: "Netherlands", label: "+31 (NL)" },
    { code: "+32", name: "Belgium", label: "+32 (BE)" },
    { code: "+33", name: "France", label: "+33 (FR)" },
    { code: "+34", name: "Spain", label: "+34 (ES)" },
    { code: "+36", name: "Hungary", label: "+36 (HU)" },
    { code: "+39", name: "Italy", label: "+39 (IT)" },
    { code: "+40", name: "Romania", label: "+40 (RO)" },
    { code: "+41", name: "Switzerland", label: "+41 (CH)" },
    { code: "+43", name: "Austria", label: "+43 (AT)" },
    { code: "+44", name: "UK", label: "+44 (UK)" },
    { code: "+45", name: "Denmark", label: "+45 (DK)" },
    { code: "+46", name: "Sweden", label: "+46 (SE)" },
    { code: "+47", name: "Norway", label: "+47 (NO)" },
    { code: "+48", name: "Poland", label: "+48 (PL)" },
    { code: "+49", name: "Germany", label: "+49 (DE)" },
    { code: "+51", name: "Peru", label: "+51 (PE)" },
    { code: "+52", name: "Mexico", label: "+52 (MX)" },
    { code: "+53", name: "Cuba", label: "+53 (CU)" },
    { code: "+54", name: "Argentina", label: "+54 (AR)" },
    { code: "+55", name: "Brazil", label: "+55 (BR)" },
    { code: "+56", name: "Chile", label: "+56 (CL)" },
    { code: "+57", name: "Colombia", label: "+57 (CO)" },
    { code: "+58", name: "Venezuela", label: "+58 (VE)" },
    { code: "+60", name: "Malaysia", label: "+60 (MY)" },
    { code: "+61", name: "Australia", label: "+61 (AU)" },
    { code: "+62", name: "Indonesia", label: "+62 (ID)" },
    { code: "+63", name: "Philippines", label: "+63 (PH)" },
    { code: "+64", name: "New Zealand", label: "+64 (NZ)" },
    { code: "+65", name: "Singapore", label: "+65 (SG)" },
    { code: "+66", name: "Thailand", label: "+66 (TH)" },
    { code: "+81", name: "Japan", label: "+81 (JP)" },
    { code: "+82", name: "South Korea", label: "+82 (KR)" },
    { code: "+84", name: "Vietnam", label: "+84 (VN)" },
    { code: "+86", name: "China", label: "+86 (CN)" },
    { code: "+90", name: "Turkey", label: "+90 (TR)" },
    { code: "+91", name: "India", label: "+91 (IN)" },
    { code: "+92", name: "Pakistan", label: "+92 (PK)" },
    { code: "+93", name: "Afghanistan", label: "+93 (AF)" },
    { code: "+94", name: "Sri Lanka", label: "+94 (LK)" },
    { code: "+95", name: "Myanmar", label: "+95 (MM)" },
    { code: "+98", name: "Iran", label: "+98 (IR)" },
    { code: "+212", name: "Morocco", label: "+212 (MA)" },
    { code: "+213", name: "Algeria", label: "+213 (DZ)" },
    { code: "+216", name: "Tunisia", label: "+216 (TN)" },
    { code: "+218", name: "Libya", label: "+218 (LY)" },
    { code: "+220", name: "Gambia", label: "+220 (GM)" },
    { code: "+221", name: "Senegal", label: "+221 (SN)" },
    { code: "+222", name: "Mauritania", label: "+222 (MR)" },
    { code: "+223", name: "Mali", label: "+223 (ML)" },
    { code: "+224", name: "Guinea", label: "+224 (GN)" },
    { code: "+225", name: "Ivory Coast", label: "+225 (CI)" },
    { code: "+226", name: "Burkina Faso", label: "+226 (BF)" },
    { code: "+227", name: "Niger", label: "+227 (NE)" },
    { code: "+228", name: "Togo", label: "+228 (TG)" },
    { code: "+229", name: "Benin", label: "+229 (BJ)" },
    { code: "+230", name: "Mauritius", label: "+230 (MU)" },
    { code: "+231", name: "Liberia", label: "+231 (LR)" },
    { code: "+232", name: "Sierra Leone", label: "+232 (SL)" },
    { code: "+233", name: "Ghana", label: "+233 (GH)" },
    { code: "+234", name: "Nigeria", label: "+234 (NG)" },
    { code: "+235", name: "Chad", label: "+235 (TD)" },
    { code: "+236", name: "Central African Republic", label: "+236 (CF)" },
    { code: "+237", name: "Cameroon", label: "+237 (CM)" },
    { code: "+238", name: "Cape Verde", label: "+238 (CV)" },
    { code: "+239", name: "Sao Tome and Principe", label: "+239 (ST)" },
    { code: "+240", name: "Equatorial Guinea", label: "+240 (GQ)" },
    { code: "+241", name: "Gabon", label: "+241 (GA)" },
    { code: "+242", name: "Congo", label: "+242 (CG)" },
    { code: "+243", name: "Democratic Republic of the Congo", label: "+243 (CD)" },
    { code: "+244", name: "Angola", label: "+244 (AO)" },
    { code: "+245", name: "Guinea-Bissau", label: "+245 (GW)" },
    { code: "+246", name: "Diego Garcia", label: "+246 (IO)" },
    { code: "+247", name: "Ascension Island", label: "+247 (AC)" },
    { code: "+248", name: "Seychelles", label: "+248 (SC)" },
    { code: "+249", name: "Sudan", label: "+249 (SD)" },
    { code: "+250", name: "Rwanda", label: "+250 (RW)" },
    { code: "+251", name: "Ethiopia", label: "+251 (ET)" },
    { code: "+252", name: "Somalia", label: "+252 (SO)" },
    { code: "+253", name: "Djibouti", label: "+253 (DJ)" },
    { code: "+254", name: "Kenya", label: "+254 (KE)" },
    { code: "+255", name: "Tanzania", label: "+255 (TZ)" },
    { code: "+256", name: "Uganda", label: "+256 (UG)" },
    { code: "+257", name: "Burundi", label: "+257 (BI)" },
    { code: "+258", name: "Mozambique", label: "+258 (MZ)" },
    { code: "+260", name: "Zambia", label: "+260 (ZM)" },
    { code: "+261", name: "Madagascar", label: "+261 (MG)" },
    { code: "+262", name: "Reunion", label: "+262 (RE)" },
    { code: "+263", name: "Zimbabwe", label: "+263 (ZW)" },
    { code: "+264", name: "Namibia", label: "+264 (NA)" },
    { code: "+265", name: "Malawi", label: "+265 (MW)" },
    { code: "+266", name: "Lesotho", label: "+266 (LS)" },
    { code: "+267", name: "Botswana", label: "+267 (BW)" },
    { code: "+268", name: "Swaziland", label: "+268 (SZ)" },
    { code: "+269", name: "Comoros", label: "+269 (KM)" },
    { code: "+290", name: "Saint Helena", label: "+290 (SH)" },
    { code: "+291", name: "Eritrea", label: "+291 (ER)" },
    { code: "+297", name: "Aruba", label: "+297 (AW)" },
    { code: "+298", name: "Faroe Islands", label: "+298 (FO)" },
    { code: "+299", name: "Greenland", label: "+299 (GL)" },
    { code: "+350", name: "Gibraltar", label: "+350 (GI)" },
    { code: "+351", name: "Portugal", label: "+351 (PT)" },
    { code: "+352", name: "Luxembourg", label: "+352 (LU)" },
    { code: "+353", name: "Ireland", label: "+353 (IE)" },
    { code: "+354", name: "Iceland", label: "+354 (IS)" },
    { code: "+355", name: "Albania", label: "+355 (AL)" },
    { code: "+356", name: "Malta", label: "+356 (MT)" },
    { code: "+357", name: "Cyprus", label: "+357 (CY)" },
    { code: "+358", name: "Finland", label: "+358 (FI)" },
    { code: "+359", name: "Bulgaria", label: "+359 (BG)" },
    { code: "+370", name: "Lithuania", label: "+370 (LT)" },
    { code: "+371", name: "Latvia", label: "+371 (LV)" },
    { code: "+372", name: "Estonia", label: "+372 (EE)" },
    { code: "+373", name: "Moldova", label: "+373 (MD)" },
    { code: "+374", name: "Armenia", label: "+374 (AM)" },
    { code: "+375", name: "Belarus", label: "+375 (BY)" },
    { code: "+376", name: "Andorra", label: "+376 (AD)" },
    { code: "+377", name: "Monaco", label: "+377 (MC)" },
    { code: "+378", name: "San Marino", label: "+378 (SM)" },
    { code: "+379", name: "Vatican City", label: "+379 (VA)" },
    { code: "+380", name: "Ukraine", label: "+380 (UA)" },
    { code: "+381", name: "Serbia", label: "+381 (RS)" },
    { code: "+382", name: "Montenegro", label: "+382 (ME)" },
    { code: "+383", name: "Kosovo", label: "+383 (XK)" },
    { code: "+385", name: "Croatia", label: "+385 (HR)" },
    { code: "+386", name: "Slovenia", label: "+386 (SI)" },
    { code: "+387", name: "Bosnia and Herzegovina", label: "+387 (BA)" },
    { code: "+389", name: "Macedonia", label: "+389 (MK)" },
    { code: "+420", name: "Czech Republic", label: "+420 (CZ)" },
    { code: "+421", name: "Slovakia", label: "+421 (SK)" },
    { code: "+423", name: "Liechtenstein", label: "+423 (LI)" },
    { code: "+500", name: "Falkland Islands", label: "+500 (FK)" },
    { code: "+501", name: "Belize", label: "+501 (BZ)" },
    { code: "+502", name: "Guatemala", label: "+502 (GT)" },
    { code: "+503", name: "El Salvador", label: "+503 (SV)" },
    { code: "+504", name: "Honduras", label: "+504 (HN)" },
    { code: "+505", name: "Nicaragua", label: "+505 (NI)" },
    { code: "+506", name: "Costa Rica", label: "+506 (CR)" },
    { code: "+507", name: "Panama", label: "+507 (PA)" },
    { code: "+508", name: "Saint Pierre and Miquelon", label: "+508 (PM)" },
    { code: "+509", name: "Haiti", label: "+509 (HT)" },
    { code: "+590", name: "Guadeloupe", label: "+590 (GP)" },
    { code: "+591", name: "Bolivia", label: "+591 (BO)" },
    { code: "+592", name: "Guyana", label: "+592 (GY)" },
    { code: "+593", name: "Ecuador", label: "+593 (EC)" },
    { code: "+594", name: "French Guiana", label: "+594 (GF)" },
    { code: "+595", name: "Paraguay", label: "+595 (PY)" },
    { code: "+596", name: "Martinique", label: "+596 (MQ)" },
    { code: "+597", name: "Suriname", label: "+597 (SR)" },
    { code: "+598", name: "Uruguay", label: "+598 (UY)" },
    { code: "+599", name: "Netherlands Antilles", label: "+599 (AN)" },
    { code: "+850", name: "North Korea", label: "+850 (KP)" },
    { code: "+852", name: "Hong Kong", label: "+852 (HK)" },
    { code: "+853", name: "Macau", label: "+853 (MO)" },
    { code: "+855", name: "Cambodia", label: "+855 (KH)" },
    { code: "+856", name: "Laos", label: "+856 (LA)" },
    { code: "+880", name: "Bangladesh", label: "+880 (BD)" },
    { code: "+886", name: "Taiwan", label: "+886 (TW)" },
    { code: "+960", name: "Maldives", label: "+960 (MV)" },
    { code: "+961", name: "Lebanon", label: "+961 (LB)" },
    { code: "+962", name: "Jordan", label: "+962 (JO)" },
    { code: "+963", name: "Syria", label: "+963 (SY)" },
    { code: "+964", name: "Iraq", label: "+964 (IQ)" },
    { code: "+965", name: "Kuwait", label: "+965 (KW)" },
    { code: "+966", name: "Saudi Arabia", label: "+966 (SA)" },
    { code: "+967", name: "Yemen", label: "+967 (YE)" },
    { code: "+968", name: "Oman", label: "+968 (OM)" },
    { code: "+970", name: "Palestine", label: "+970 (PS)" },
    { code: "+971", name: "United Arab Emirates", label: "+971 (AE)" },
    { code: "+972", name: "Israel", label: "+972 (IL)" },
    { code: "+973", name: "Bahrain", label: "+973 (BH)" },
    { code: "+974", name: "Qatar", label: "+974 (QA)" },
    { code: "+975", name: "Bhutan", label: "+975 (BT)" },
    { code: "+976", name: "Mongolia", label: "+976 (MN)" },
    { code: "+977", name: "Nepal", label: "+977 (NP)" },
    { code: "+992", name: "Tajikistan", label: "+992 (TJ)" },
    { code: "+993", name: "Turkmenistan", label: "+993 (TM)" },
    { code: "+994", name: "Azerbaijan", label: "+994 (AZ)" },
    { code: "+995", name: "Georgia", label: "+995 (GE)" },
    { code: "+996", name: "Kyrgyzstan", label: "+996 (KG)" },
    { code: "+998", name: "Uzbekistan", label: "+998 (UZ)" }
];